"""Add PA tracking fields

Revision ID: 0921d4dfbda0
Revises: 8020959295c4
Create Date: 2026-06-16 21:29:11.273479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0921d4dfbda0'
down_revision: Union[str, None] = '8020959295c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream_stats', sa.Column('pa_received_this_stream', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream_stats', 'pa_received_this_stream')
    # ### end Alembic commands ###