"""Initial migration: users, stream_sessions, stream_stats

Revision ID: 20af8aaf1ea2
Revises: 
Create Date: 2026-06-14 01:54:15.245217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20af8aaf1ea2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winner_1_nick', sa.String(length=100), nullable=True),
    sa.Column('winner_2_nick', sa.String(length=100), nullable=True),
    sa.Column('winner_3_nick', sa.String(length=100), nullable=True),
    sa.Column('winner_1_prize', sa.String(length=200), nullable=True),
    sa.Column('winner_2_prize', sa.String(length=200), nullable=True),
    sa.Column('winner_3_prize', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=True),
    sa.Column('nick', sa.String(length=100), nullable=False),
    sa.Column('premium_streams_left', sa.Integer(), nullable=True),
    sa.Column('lifetime_streams_with_premium', sa.Integer(), nullable=True),
    sa.Column('lifetime_boxes_opened', sa.Integer(), nullable=True),
    sa.Column('lifetime_tanks_lt', sa.Integer(), nullable=True),
    sa.Column('lifetime_tanks_st', sa.Integer(), nullable=True),
    sa.Column('lifetime_tanks_tt', sa.Integer(), nullable=True),
    sa.Column('lifetime_tanks_pt', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_nick'), 'users', ['nick'], unique=True)
    op.create_index(op.f('ix_users_vk_id'), 'users', ['vk_id'], unique=True)
    op.create_table('stream_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('current_bm', sa.Integer(), nullable=True),
    sa.Column('activations_count', sa.Integer(), nullable=True),
    sa.Column('last_activation_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['stream_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_stats_session_id'), 'stream_stats', ['session_id'], unique=False)
    op.create_index(op.f('ix_stream_stats_user_id'), 'stream_stats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stream_stats_user_id'), table_name='stream_stats')
    op.drop_index(op.f('ix_stream_stats_session_id'), table_name='stream_stats')
    op.drop_table('stream_stats')
    op.drop_index(op.f('ix_users_vk_id'), table_name='users')
    op.drop_index(op.f('ix_users_nick'), table_name='users')
    op.drop_table('users')
    op.drop_table('stream_sessions')
    # ### end Alembic commands ###