"""Add pending_boxes to User

Revision ID: 2e5fd1a64d73
Revises: ad7ba56903fb
Create Date: 2026-06-15 21:10:41.449558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5fd1a64d73'
down_revision: Union[str, None] = 'ad7ba56903fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###