"""Add processed_messages table

Revision ID: 62f61f3153a0
Revises: 20af8aaf1ea2
Create Date: 2026-06-14 03:08:36.604748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f61f3153a0'
down_revision: Union[str, None] = '20af8aaf1ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('msg_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_messages_msg_id'), 'processed_messages', ['msg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_messages_msg_id'), table_name='processed_messages')
    op.drop_table('processed_messages')
    # ### end Alembic commands ###