"""Add PA chance tracking fields

Revision ID: 8020959295c4
Revises: a42c6b4fe318
Create Date: 2026-06-16 20:59:13.911192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8020959295c4'
down_revision: Union[str, None] = 'a42c6b4fe318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream_sessions', sa.Column('pa_received_this_stream', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('boxes_since_last_pa', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'boxes_since_last_pa')
    op.drop_column('stream_sessions', 'pa_received_this_stream')
    # ### end Alembic commands ###