"""Add pending_boxes to User

Revision ID: a42c6b4fe318
Revises: 2e5fd1a64d73
Create Date: 2026-06-15 21:19:53.182056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42c6b4fe318'
down_revision: Union[str, None] = '2e5fd1a64d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_boxes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_boxes')
    # ### end Alembic commands ###